Add tests for stage 3 proposal error cause
tc39/test262 pull request #2965
Opened 2021-03-18 03:44 UTC by legendecas

2021-03-26 23:25 UTC, jugglinmike requested changes
Thanks for the patch, @legendecas!

Test262 has some automated checks that run against all pull requests, and the results are available at the bottom of each GitHub Pull Request page. The checks are labeled as "build & lint tests." For this Pull Request, the check is reporting a problem:

    Linting complete. 3 errors found.
    /home/circleci/test262/test/built-ins/Error/cause_property.js: HARNESS - verifyConfigurable & verifyProperty may not be used in the same file
    /home/circleci/test262/test/built-ins/NativeErrors/AggregateError/cause-property.js: HARNESS - verifyConfigurable & verifyProperty may not be used in the same file
    /home/circleci/test262/test/built-ins/NativeErrors/cause_property_native_error.js: HARNESS - verifyConfigurable & verifyProperty may not be used in the same file

The `verifyProperty` is capable of verifying the entire property descriptor. Would you mind updating your patch to use that instead of `verifyNotEnumerable`, `verifyWritable`, and `verifyConfigurable`?

(We recommend using `verifyProperty` instead of a combination of the more targeted functions because it's so tricky to get the sequence of those functions right. As a bonus, `verifyProperty` fails with a message describing *every* violated expectation--implementers will only see the *first* violation from the more targeted functions.)

Here are some ideas about improving coverage:

- InstallErrorCause has two observable behaviors that we're not testing yet. They're strange edge cases, but those make them the most likely for implementers to miss!

  - > 1. If Type(options) is Object and ? HasProperty(options, "cause") is true, then

    Could you add a test for when HasProperty returns an abrupt completion?

  - > Let cause be ? Get(options, "cause").

    Could you add a test for when Get returns an abrupt completion?

- In all cases, the error "message" is installed before the error "cause." This might seem inconsequential, but if implementers get it backwards, then that could lead to interoperability bugs. For example:

      var sequence = [];
      new Error(
        {toString() { sequence.push('toString'); }},
        {get cause() { sequence.push('cause'); }}
      );

2021-03-26 23:25 UTC, jugglinmike commented on test/built-ins/Error/cause_property.js
> +var cause = new Error("my-cause");
Although we expect developers to set the `cause` to Error instances, there's nothing in the proposal which requires that. Would you mind using a plain Object instead? That will help verify that the feature is value-agnostic without reducing the test's ability to assert identity.

2021-04-09 18:36 UTC, jugglinmike commented
Hi again, @legendecas. Would you like a hand making those changes?

2021-04-12 06:01 UTC, legendecas commented
@jugglinmike sorry for the delay, just updated the tests to include your great suggestions. thanks.

2021-04-23 18:44 UTC, jugglinmike approved these changes
Hi there, @legendecas! I noticed that you pushed up a new version yesterday, so I've taken another look. (In the future, if you could avoid rewriting previously-submitted commits, that will make it easier for folks to review your changes.)

This new version is great! There are a few minor improvements that we can still make, but they don't concern correctness, so I'll make a follow-up patch to discuss further.

However, there was one issue that was related to correctness: the Proxy constructor was being invoked without the `new` operator. That prevented the test from passing in conforming runtimes. Since the correction was straightforward and since I'd like to make these tests available to consumers as soon as possible, I've gone ahead and pushed a fix to this branch. Hope you don't mind!

2021-04-23 18:45 UTC, merged

2021-04-26 03:30 UTC, legendecas commented
@jugglinmike thanks a lot for the correctness update! It is not quite easy to check the test correctness with tools that I'm aware of. I'm so sorry for the poor updates 😵 .