Add test for [[Description]] from `Symbol.for`
tc39/test262 pull request #2970
Opened 2021-04-09 22:09 UTC by jugglinmike

Resolves gh-2967. I reviewed the project's coverage for the rest of this algorithm, and it looks okay to me.

2021-04-18 18:06 UTC, shvaikalesh approved these changes

2021-04-18 18:06 UTC, shvaikalesh commented on test/built-ins/Symbol/for/description.js
> +features: [Symbol]
```suggestion
features: [Symbol, Symbol.prototype.description]
```

2021-04-19 15:09 UTC, leobalter requested changes
@jugglinmike The test looks good and it is just missing the feature tag as pointed out by @shvaikalesh.

A small nit pick, thou. I believe this test file should be at [test/built-ins/Symbol/prototype/description](https://github.com/tc39/test262/tree/main/test/built-ins/Symbol/prototype/description) and that folder might be missing other tests to capture description from ToString coerced values.

The decision on the file location might be subjective and it's ok to not go through that path.

2021-04-23 16:55 UTC, jugglinmike commented
Thanks for reviewing this!

> just missing the feature tag as pointed out by @shvaikalesh.

All set

> I believe this test file should be at test/built-ins/Symbol/prototype/description

Yeah, the test necessarily uses two different APIs, making the placement a little ambiguous. I chose the `for/` directory because we're specifically interested in how the `[[Description]]` internal slot is defined, not how the `[[Description]]` internal slot is referenced (the existing tests verify the latter).

> that folder might be missing other tests to capture description from ToString coerced values.

I can help with that. I don't see any string coercion in that algorithm, though--could you say more about what you have in mind?

2021-05-04 18:04 UTC, rwaldron commented
@leobalter are you good with @jugglinmike's response?

2021-05-04 22:30 UTC, leobalter commented
Yes, I just don't have the bandwidth to expand my thoughts on the ToString coercion, but hopefully I can explore it in a near future.

2021-05-13 23:34 UTC, jugglinmike commented
Thanks, @leobalter! Would you mind formally registering your approval using the GitHub.com UI? At some point, this became mandatory for Test262 pull requests.

2021-05-14 00:09 UTC, leobalter approved these changes

2021-05-14 01:16 UTC, merged