Add tests for JSON modules
tc39/test262 pull request #2999
Opened 2021-05-28 20:41 UTC by jugglinmike

Designate the files which are intended to be interpreted as JSON modules
via a distinct file name suffix. Differentiating JSON files in this way
will assist consumers which require special handling of such files (e.g.
web browsers).

Change the pattern used to designate "fixture" files so that it may be
applied to files used for JSON modules.

Increment the project version number to alert consumers of this change
in interpreting instructions.

2021-05-28 21:47 UTC, rwaldron requested changes
Please check linting errors

2021-05-28 23:07 UTC, jugglinmike commented
Got it Rick. I've split the infrastructural changes into a dedicated commit which precedes the commit introducing the "JSON modules" tests.

2021-05-29 00:02 UTC, rwaldron approved these changes

2021-05-29 00:02 UTC, merged

2022-08-26 08:21 UTC, wangxiang365 commented
****