Add tests for proposal array find from last
tc39/test262 pull request #3045
Opened 2021-07-16 05:06 UTC by Kingwl

This proposal is currently at "stage 3".

2021-07-16 14:00 UTC, rwaldron requested changes
Please add to features.txt: 

```
# Array.prototype.findLast & Array.prototype.findLastIndex
# https://github.com/tc39/proposal-array-find-from-last
array-find-from-last
```


Add to meta data in all files: 

```
features: [array-find-from-last]
```


Fix all license headers to read: 

```
// Copyright (C) 2021 Microsoft. All rights reserved.

2021-07-19 17:30 UTC, rwaldron commented
Thanks for the updates. I will review this week

2021-07-19 20:16 UTC, jugglinmike requested changes
Thanks for writing these!

2021-07-20 08:56 UTC, Kingwl commented
Thanks for the review.

2021-07-20 18:59 UTC, rwaldron approved these changes

2021-07-20 19:00 UTC, rwaldron commented
Once @jugglinmike give this R+, it's good to go.

2021-07-26 17:34 UTC, jugglinmike requested changes
Looks like there are few incorrect assertions. Could you take a look?

2021-07-27 10:18 UTC, Kingwl commented
Sorry. I have missed these case.

2021-07-28 17:50 UTC, rwaldron approved these changes

2021-07-28 18:00 UTC, rwaldron commented
Manually merged

2021-07-28 18:00 UTC, closed without merging

2021-07-29 01:40 UTC, Kingwl commented
Thanks!

2021-07-29 04:07 UTC, jugglinmike commented
These tests include the error that gh-3113 fixed in similar tests. @Kingwl would you mind making the same correction? /cc @marjakh

2021-07-31 02:16 UTC, jugglinmike commented
I had some time today, so I wrote that patch: gh-3126