Add tests for Temporal.Calendar.prototype.(year|month*|day)
tc39/test262 pull request #3050
Opened 2021-07-17 09:04 UTC by FrankYFTang

https://github.com/tc39/test262/issues/3002

@jugglinmike @ryzokuken @Ms2ger

2021-07-19 17:34 UTC, rwaldron requested changes
Please fix the directory names.

2021-07-19 18:17 UTC, FrankYFTang commented
PTAL

2021-08-05 05:25 UTC, FrankYFTang commented
Split tests, add error throwing tests. PTAL

2021-08-05 22:31 UTC, rwaldron approved these changes

2021-08-05 22:31 UTC, merged