Add tests for Temporal.Calendar.prototype.dayOf*
tc39/test262 pull request #3051
Opened 2021-07-17 09:20 UTC by FrankYFTang

https://github.com/tc39/test262/issues/3002

@jugglinmike @ryzokuken @Ms2ger

2021-07-19 17:34 UTC, rwaldron requested changes
Please fix the directory names.

2021-07-19 18:19 UTC, FrankYFTang commented
PTAL

2021-07-19 21:04 UTC, FrankYFTang commented
It might be hard to review the test based on the current spec text due to https://github.com/tc39/proposal-temporal/issues/1641

2021-07-19 22:21 UTC, ptomato commented on test/built-ins/Temporal/Calendar/prototype/dayOfYear/plain-date-time.js
> +return the day of year.
I think this has to be indented or it's not valid YAML (test262-stream balks at it)

2021-08-05 22:03 UTC, FrankYFTang commented
@jugglinmike I think I fulfull what you ask me to do from other PR 
PTAL

2021-08-05 22:31 UTC, rwaldron approved these changes

2021-08-05 22:31 UTC, merged