Add tests for Intl Enumeration API
tc39/test262 pull request #3186
Opened 2021-09-07 13:01 UTC by anba

Covers the usual surface tests and additional functionality tests which were
upstreamed from existing tests in SpiderMonkey.

Fixes #3131

2021-09-07 21:51 UTC, rwaldron commented
@anba three lint issues: 

```
/home/circleci/test262/test/intl402/Intl/supportedValuesOf/builtin.js: FRONTMATTER - Unrecognized fields: include
/home/circleci/test262/test/intl402/Intl/supportedValuesOf/numberingSystems-with-simple-digit-mappings.js: INCLUDES - Unused include: "testIntl.js"
/home/circleci/test262/test/intl402/NumberFormat/prototype/format/numbering-systems.js: INCLUDES - Unused include: "testIntl.js"
```

2021-09-07 21:52 UTC, rwaldron requested changes
@anba three lint issues: 

```
/home/circleci/test262/test/intl402/Intl/supportedValuesOf/builtin.js: FRONTMATTER - Unrecognized fields: include
/home/circleci/test262/test/intl402/Intl/supportedValuesOf/numberingSystems-with-simple-digit-mappings.js: INCLUDES - Unused include: "testIntl.js"
/home/circleci/test262/test/intl402/NumberFormat/prototype/format/numbering-systems.js: INCLUDES - Unused include: "testIntl.js"
```

2021-09-07 22:20 UTC, leobalter reviewed
Adding the suggestions here that might help speeding up the process to land this PR.

2021-09-07 22:20 UTC, leobalter commented on test/intl402/Intl/supportedValuesOf/numberingSystems-with-simple-digit-mappings.js
> +includes: [testIntl.js]
```suggestion
```

2021-09-07 22:20 UTC, leobalter commented on test/intl402/NumberFormat/prototype/format/numbering-systems.js
> +includes: [testIntl.js]
```suggestion
```

2021-09-07 22:20 UTC, leobalter commented on test/intl402/Intl/supportedValuesOf/builtin.js
> +include: [isConstructor.js]
```suggestion
includes: [isConstructor.js]
```

2021-09-08 09:34 UTC, anba commented
Updates:
- 9e88c32d067a65e40060ae0625386e76e1023197
Add `numberingSystemDigits` to the list of exported objects. This resolves the unused include warnings for "testIntl.js".

- 069f2e8a9eed63604795426e89dae4566bdfd0b7
Fixed `include` &rarr; `includes` typo. And then added "Reflect.construct" to the features list to avoid a new linter warning.

2021-09-08 13:26 UTC, rwaldron approved these changes

2021-09-08 13:29 UTC, merged