Add test for byteOffset coverage in %typedarray%.prototype.copywithin
tc39/test262 pull request #3187
Opened 2021-09-07 15:49 UTC by legendecas

2021-09-07 21:54 UTC, rwaldron requested changes

2021-09-07 21:54 UTC, rwaldron commented on test/built-ins/TypedArray/prototype/copyWithin/byteoffset.js
> +  print(ta);
Remove this please

2021-09-07 21:54 UTC, rwaldron commented on test/built-ins/TypedArray/prototype/copyWithin/byteoffset.js
> +    compareArray(
Please use the newer `assert.compareArray()` API. Thank you

2021-09-07 21:54 UTC, rwaldron commented on test/built-ins/TypedArray/prototype/copyWithin/byteoffset.js
> +    compareArray(
Please use the newer `assert.compareArray()` API. Thank you

2021-09-09 06:22 UTC, legendecas commented
@rwaldron Thanks for the suggestion, updated! :)

2021-09-10 19:05 UTC, rwaldron approved these changes

2021-09-10 19:05 UTC, merged