test(Intl.DurationFormat.prototype): check prototype attributes
tc39/test262 pull request #3331
Opened 2021-11-28 01:02 UTC by EarthyOrange

#3305

2021-12-02 14:41 UTC, rwaldron commented
@EarthyOrange thanks for the contribution! According to CI, there is an issue here that's easily resolvable and I'll leave a comment in-line to show what needs to be fixed.

2021-12-02 14:44 UTC, rwaldron requested changes
In addition to those changes, please add a new feature to https://github.com/tc39/test262/blob/main/features.txt, which should be: 

```
# Intl.DurationFormat
# https://github.com/tc39/proposal-intl-duration-format
Intl.DurationFormat
```

2021-12-02 14:44 UTC, rwaldron commented on test/intl402/DurationFormat/prototype/prototype_attributes.js
> +features: [Intl.DurationFormat.prototype]
```suggestion
features: [Intl.DurationFormat]
```

2021-12-02 14:44 UTC, rwaldron commented on test/intl402/DurationFormat/prototype/toStringTag.js
> +features: [Symbol.toStringTag]
```suggestion
features: [Intl.DurationFormat, Symbol.toStringTag]
```

2021-12-03 00:33 UTC, EarthyOrange commented
> In addition to those changes, please add a new feature to https://github.com/tc39/test262/blob/main/features.txt, which should be:
> 
> ```
> # Intl.DurationFormat
> # https://github.com/tc39/proposal-intl-duration-format
> Intl.DurationFormat
> ```

Did adding these lines to the features.txt appease the CI?

2021-12-04 00:53 UTC, rwaldron commented
@EarthyOrange 
> Did adding these lines to the features.txt appease the CI?

According to the CI report, it sure did!

2021-12-04 00:53 UTC, rwaldron approved these changes

2021-12-04 00:53 UTC, merged