added tests for groupBy
tc39/test262 pull request #3354
Opened 2021-12-15 11:24 UTC by polsevev

Added tests for proposal Array Grouping groupBy

CC @codehag

2021-12-15 17:30 UTC, rwaldron commented
Again, very cool that you jumped right in on these :D we'll also go over this one during our video call on Friday. See you then!!

2021-12-15 17:32 UTC, ljharb reviewed
This looks great! I compared it against my polyfill's tests, and noticed this PR isn't testing that a non-function callbackfn throws a TypeError, and that the [[Prototype]] of the returned object is null.

2021-12-17 16:34 UTC, rwaldron commented on test/built-ins/Array/prototype/groupBy/callback-arg.js
> +
```suggestion
features: [Array.prototype.groupBy]
```

2021-12-17 16:41 UTC, rwaldron commented on test/built-ins/Array/prototype/groupBy/null.js
> +  Array.prototype.groupBy.call(null,null);
```suggestion
Array.prototype.groupBy.call(null, () => {
  throw new Test262Error();
});
```

2021-12-17 16:41 UTC, rwaldron commented on test/built-ins/Array/prototype/groupBy/null.js
> +  Array.prototype.groupBy.call(null,null);
And combine all of the invalid this tests into one file :)

2022-01-06 16:57 UTC, legendecas commented on test/built-ins/Array/prototype/groupBy/callback-arg.js
> +const map = arr.groupBy.call(sentinel, (n,i,testArr) => {
IIUC, `LengthOfArrayLike` of the `sentinel` is 0, the callback won't be called in this case.

2022-01-10 19:43 UTC, leobalter requested changes
The tests are good, I added a few suggestions only.

You may also wanna test:

- the return type of groupBy
- assert this value inside the callbackfn w/ and w/o `thisArg`
- non-callback values for callbackfn
- non valid values for the this value
- tainted callbackfns (throwing an exception).
- callbackfn calls with terse arrays like `[,,,1,,2]`
- array like values for the this value, e.g. `[].groupBy.call({length: 2, '1': 'foo'}, callbackfn);`

2022-01-10 19:43 UTC, leobalter commented on test/built-ins/Array/prototype/groupBy/length.js
> +});
```suggestion
verifyProperty(Array.prototype.groupBy, "length", {
  value: 1,
  enumerable: false,
  writable: false,
  configurable: true
});
```

2022-01-10 19:43 UTC, leobalter commented on test/built-ins/Array/prototype/groupBy/name.js
> +});
```suggestion
verifyProperty(Array.prototype.groupBy, "name", {
  value: "groupBy",
  enumerable: false,
  writable: false,
  configurable: true
});
```

2022-01-10 19:43 UTC, leobalter commented on test/built-ins/Array/prototype/groupBy/undefined.js
> +});
```suggestion
var calls = 0;

assert.throws(TypeError, function() {
  Array.prototype.groupBy.call(undefined, () => calls++);
});
assert.sameValue(calls, 0, "callbackfn should not be called");
```

2022-01-10 19:43 UTC, leobalter commented on test/built-ins/Array/prototype/groupBy/emptyList.js
> +assert.sameValue(Object.keys(obj).length, 0);
You might also benefit testing that `obj` is different to the original array and asserting the callbackfn is not called. Something like:

```js
var calls = 0;
const original = [];
const obj = original.groupBy(() => calls++);

assert.sameValue(calls, 0, "callback function should not be called");
assert.notSameValue(original, obj, "groupBy returns a different object");
assert.sameValue(Object.keys(obj).length, 0);
```

2022-06-08 13:37 UTC, hemanth commented
This should be `group` instead of `groupBy` now.

2022-09-01 23:24 UTC, jridgewell reviewed
https://github.com/tc39/test262/pull/3354#pullrequestreview-848251319

> the return type of groupBy

done.

> assert this value inside the callbackfn w/ and w/o thisArg

done.

> non-callback values for callbackfn

done.

> non valid values for the this value

done.

> tainted callbackfns (throwing an exception).

Do we have to?

> callbackfn calls with terse arrays like [,,,1,,2]

done.

> array like values for the this value, e.g. [].groupBy.call({length: 2, '1': 'foo'}, callbackfn);

Done.

2022-09-13 21:57 UTC, ptomato approved these changes
Thanks for resuming this PR, and apologies that it took some time to get around to it. (I'll start on groupToMap as soon as possible.) I think this is basically ready to merge. Some small suggestions, but keeping in mind how long this has already taken to review, I've made them into GitHub suggestions that you can just click to accept or not, so that the review process don't cause any more delay on this PR.

I have some suggestions for additional things that could be tested, but for the same reason I wouldn't say that they should block this PR. They can be added in a second PR if you are so inclined:
- Test throwing on an arraylike with a value of its `length` property that can't be converted to an integer, or a getter that throws
- Test throwing in step 6.b if _Pk_ is a property with a getter that throws
- Test throwing if the callback returns a value that can't be converted to a property key (e.g. an object with a toString method that throws)

Thanks again for resuming this work!

2022-09-13 21:57 UTC, ptomato commented on test/built-ins/Array/prototype/group/callback-arg.js
> +let calls = 0;
`sentinel` is not used, this seems to be left over from one of the other tests?
```suggestion
let calls = 0;
```

2022-09-13 21:57 UTC, ptomato commented on test/built-ins/Array/prototype/group/emptyList.js
> +description: Array.prototype.group populates object with correct keys and values
This description doesn't quite seem to fit the test; maybe something like this?
```suggestion
description: Callback is not called and object is not populated if the array is empty
```

2022-09-13 21:57 UTC, ptomato commented on test/built-ins/Array/prototype/group/groupLength.js
> +description: Array.prototype.group populates object with correct keys and values
Same here, I'd suggest something like:
```suggestion
description: Callback can return numbers that are converted to property keys
```

2022-09-13 21:57 UTC, ptomato commented on test/built-ins/Array/prototype/group/sparse-array.js
> +assert.sameValue(2 in obj['key'], true);
`assert.sameValue(..., true)` is going to produce a pretty context-less error message if it fails, something like "Expected true but got false". Plain `assert()` won't be any better (at least it's shorter) but I'd recommend adding assertion messages here:
```suggestion
assert(0 in obj['key'], 'group has a first element');
assert(1 in obj['key'], 'group has a second element');
assert(2 in obj['key'], 'group has a third element');
```

2022-09-13 21:57 UTC, ptomato commented on test/built-ins/Array/prototype/group/sparse-array.js
> +description: Array.prototype.group populates object with correct keys and values
```suggestion
description: Array.prototype.group adds undefined to the group for sparse arrays
```

2022-09-13 22:00 UTC, ptomato commented
> > tainted callbackfns (throwing an exception).
> 
> Do we have to?

Would be nice, but as with the other suggestions I don't see a need to block this PR on having that.

Another one I thought of: shortening and lengthening the array during the iteration.

2022-09-14 01:43 UTC, jridgewell commented
> Test throwing on an arraylike with a value of its length property that can't be converted to an integer, or a getter that throws

Done.

> Test throwing in step 6.b if Pk is a property with a getter that throws

Done.

> Test throwing if the callback returns a value that can't be converted to a property key (e.g. an object with a toString method that throws)

Done.

> tainted callbackfns (throwing an exception).

Done.

2022-09-14 18:02 UTC, ptomato approved these changes
Awesome, thanks!

2022-09-14 18:02 UTC, merged