Temporal: Add temporal case insensitive tests
tc39/test262 pull request #3655
Opened 2022-09-07 09:19 UTC by Aditi-1400

This PR adds tests for the normative change: https://github.com/tc39/proposal-temporal/pull/2395

2022-09-07 17:22 UTC, ptomato requested changes
Looks good (I reviewed a representative subset of the tests) but I think we need to have the argument be some mixed-case form of "iso8601" or "UTC" in all cases. Implementations aren't required to support "japanese" and "Etc/GMT+1", so those tests might fail. So, I'd recommend testing only the ISO calendar and UTC time zone, and then adding just a few representative tests in the `intl402/` directory (maybe just for `new TimeZone`, `TimeZone.from`, `new Calendar`, `Calendar.from`) for mixed-case versions of other time zones and calendars.

2022-09-08 18:47 UTC, ptomato approved these changes
Looks good now, thanks for updating!

I noticed something with the ESIDs that I missed on the first review, sorry about that. (the ESID should be equal to the part of the spec text URL after `#`, e.g. for the [Temporal.Calendar constructor](https://tc39.es/proposal-temporal/#sec-temporal.calendar) it's `sec-temporal.calendar`.) I think I've identified all the places where this is an issue, so we can just add the suggestions before merging.

I'll mark it now as "awaiting consensus" so we can merge it after the plenary.

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/Now/zonedDateTimeISO/timezone-case-insensitive.js
> +esid: sec-temporal.now.prototype.zoneddatetimeiso
```suggestion
esid: sec-temporal.now.zoneddatetimeiso
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/PlainDate/calendar-case-insensitive.js
> +esid: sec-temporal.plaindate.prototype.constructor
```suggestion
esid: sec-temporal.plaindate
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/PlainDateTime/calendar-case-insensitive.js
> +esid: sec-temporal.plaindatetime.prototype.constructor
```suggestion
esid: sec-temporal.plaindatetime
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/PlainDateTime/from/argument-propertybag-calendar-case-insensitive.js
> +esid: sec-temporal.plaindatetime.prototype.from
```suggestion
esid: sec-temporal.plaindatetime.from
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/PlainMonthDay/calendar-case-insensitive.js
> +esid: sec-temporal.plainmonthday.prototype.constructor
```suggestion
esid: sec-temporal.plainmonthday
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/PlainMonthDay/from/argument-propertybag-calendar-case-insensitive.js
> +esid: sec-temporal.plainmonthday.prototype.from
```suggestion
esid: sec-temporal.plainmonthday.from
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/PlainYearMonth/calendar-case-insensitive.js
> +esid: sec-temporal.plainyearmonth.prototype.constructor
```suggestion
esid: sec-temporal.plainyearmonth
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/PlainYearMonth/from/argument-propertybag-calendar-case-insensitive.js
> +esid: sec-temporal.plainyearmonth.prototype.from
```suggestion
esid: sec-temporal.plainyearmonth.from
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/TimeZone/from/timezone-case-insensitive.js
> +esid: sec-temporal.timezone.prototype.from
```suggestion
esid: sec-temporal.timezone.from
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/ZonedDateTime/calendar-case-insensitive.js
> +esid: sec-temporal.zoneddatetime.prototype.constructor
```suggestion
esid: sec-temporal.zoneddatetime
```

2022-09-08 18:47 UTC, ptomato commented on test/built-ins/Temporal/ZonedDateTime/from/argument-propertybag-calendar-case-insensitive.js
> +esid: sec-temporal.zoneddatetime.prototype.from
```suggestion
esid: sec-temporal.zoneddatetime.from
```

2022-09-10 16:07 UTC, Aditi-1400 commented
Oops! 🙈 Thanks for all the suggestions! :)

2022-09-13 18:26 UTC, ptomato approved these changes
The normative change that this tests, achieved consensus at the September 2022 TC39 meeting.

2022-09-13 18:32 UTC, merged