Test the format of a German date with a short weekday and no year
tc39/test262 pull request #3739
Opened 2022-12-02 11:46 UTC by MidnightDesign

I've stumbled upon an inconsistency between V8 and JavaScriptCore. Formatting a date with a short weekday and no year in German results in the following strings:

V8: `Sa., 24. Dezember`
JavaScriptCore: `Sa. 24. Dezember` (no comma after the weekday)

When the year is included (`year: 'numeric'`), JavaScriptCore does add a comma.

2022-12-02 12:48 UTC, Ms2ger commented
Please add copyright and frontmatter: https://github.com/tc39/test262/blob/main/CONTRIBUTING.md#test-case-style

On what basis did you decide which implementation was correct?

2022-12-02 12:50 UTC, MidnightDesign commented
> On what basis did you decide which implementation was correct?

Because of the consistent behavior when including the year.

2022-12-02 12:59 UTC, MidnightDesign commented
Can someone help me out with the esid? I don't think the local styles themselves are defined in the spec, are they?

2022-12-02 13:30 UTC, MidnightDesign commented
I'm not sure if I'm reading it right, but if I do, I've found a source: In [CLDR 42](http://unicode.org/Public/cldr/42/cldr-common-42.0.zip), in the file `common/main/de.xml`, there's the entry
> `<dateFormatItem id="MMMMEd">E, d. MMMM</dateFormatItem>`

2022-12-02 19:26 UTC, ptomato reviewed
Hi @MidnightDesign, thanks for contributing! We really appreciate it when people investigate browser bugs and are sufficiently motivated to make the web better that they make it all the way here to test262 :smile:

Unfortunately this kind of test raises questions about what's in scope for test262 that don't have a clear answer. As you correctly noted, the local styles themselves are not defined in the spec. The closest we get is the [definition of [[LocaleData]]](https://tc39.es/ecma402/#sec-intl.datetimeformat-internal-slots), specifically the [[LocaleData]].[[<_locale_>]].[[formats]].[[<_calendar_>]].[[pattern]] field. The contents are "implementation-defined" which technically puts this out of scope for test262 because an engine could pretty much have any value they like and still be compliant. In practice, of course, that's not what happens: engines either have no locale data and no `Intl` object at all, or sensible locale data.

Additionally we don't want to couple tests too closely to the locale data, because sometimes the formats do get updated from the CLDR side. It's not good if engines update their locale data and tests start failing (which [recently happened](https://github.com/tc39/test262/pull/3676)). That leads to untrustworthy compliance statistics.

On the other hand, I think everyone acknowledges it's beneficial for the web if browsers produce the same output in locale methods. So, pragmatically, we do have a few tests that are specifically coupled to the locale data ([example](https://github.com/tc39/test262/blob/main/test/intl402/DateTimeFormat/prototype/format/timedatestyle-en.js)).

I'm sorry I don't have a better answer for you. Probably there are divergent opinions among test262 maintainers and consumers as well. I understand a complicated response to a simple PR is probably demotivating, but I hope this helps explain the context and competing priorities that exist around this kind of test.

My personal opinion on a way forward would be the following, but others may disagree.

I tested your example using the [eshost](https://github.com/bterlson/eshost) tool and found that on all three major browsers, the output has the comma. So I assume your results on JSC are on an old version, and I'd start by looking at the source code of JSC to see what bug they fixed that changed the result to include the comma. (e.g. Outdated CLDR data? Post-processing that other engines don't do?) Ideally that would surface a bug that we could test more generally in a test262 test that would be less tightly coupled to a specific version of the locale data. If that proves impossible, then depending on what the cause was, it might be worth having a tightly coupled test.

2022-12-02 20:16 UTC, MidnightDesign commented
@ptomato Thank you for your very detailed response and trying to not discourage me. I will go back and try to make this more reproducible in the next days. But I do remember that I definitely used the latest Safari on the latest OSX.

Just to give you some background on why this is so important to me: I'm using Next.js which renders the page using Node on the server and then hydrates it on the client. If the HTML of the server and the client disagree, React throws an error. Well, in this case, Node.js renders the date differently from Safari, and this is spamming our Rollbar:

![image](https://user-images.githubusercontent.com/743172/205377943-8ff3520f-077a-4add-826b-30e70676c5d7.png)

So I'm not just very picky about my commas in dates, but there's an actual problem I'm trying to solve. : )

2022-12-02 20:24 UTC, ptomato commented
Cool, then I think my advice about JSC still applies, but maybe in reverse; we must both be testing with different versions, and one is newer than the other :smile:

According to eshost, the version I tested with was https://github.com/WebKit/WebKit/commit/41769648c46baef691c1b892b0aacd51ee51e784. I see a date of 2022-05-19 on that commit.

2022-12-05 08:16 UTC, MidnightDesign commented on test/intl402/DateTimeFormat/prototype/format/german-weekday-no-year.js
> +assert.sameValue(dtf.format(new Date(2022, 12, 24)), "Sa., 24. Dezember", "German weekday without year");
Right, forgot about that. Thanks!

2022-12-05 08:18 UTC, MidnightDesign commented on test/intl402/DateTimeFormat/prototype/format/german-weekday-no-year.js
> +description: >
Thank you, I added it.

2022-12-05 08:19 UTC, MidnightDesign commented on test/intl402/DateTimeFormat/prototype/format/german-weekday-no-year.js
> +---*/
Added the tag. Thanks.

2022-12-07 13:09 UTC, MidnightDesign commented
> Another possibility that occurred to me is that Safari the browser could be using different internationalization data than JSC does when built by itself?

I would pretty much assume that that's the case. Well, I guess I'll just have to add the year everywhere. Should I go ahead and close this PR?

2022-12-15 08:16 UTC, MidnightDesign commented
For what it's worth, Safari also renders date time ranges in German differently from all other engines: It uses a different kind of dash/hyphen and different kinds of spaces around it.

2022-12-17 21:38 UTC, ptomato commented
I'm still pretty sure that must be due to a CLDR update. (https://github.com/tc39/test262/pull/3676 is the recent fallout in test262 due to CLDR 42 using different kinds of spaces than previously.)

2023-02-01 00:35 UTC, ptomato requested changes
@MidnightDesign Thanks for waiting, I still owe you an answer on this.

I discussed it with some of our other maintainers and while this is indeed out of scope, there is precedent for specific bugs, and I think there's some benefit.

I also did a bit of digging and as far as I can tell, the `E, d. MMMM` format has not changed since 2014 in CLDR. JavaScriptCore seems to have the correct behaviour, with the comma, as of current head. So, whatever went wrong with the localization data of this buggy version of Safari, may well have been prevented by such a test.

I'd ask that we do structure the test so that it's robust against unrelated things changing in the CLDR data, for example the space separator issue that I mentioned earlier. So, for example, I think it'd be sufficient to ensure the string contains the substring `Sa.,` rather than comparing the whole string.

2026-09-03 04:59 UTC, MidnightDesign commented
@ptomato I just stumbled upon this old PR of mine. Sorry for not responding for over 3 years... : ) I just updated the assertion.

Edit: Feel free to close this if it doesn't belong in test262.

2026-09-21 20:03 UTC, ptomato approved these changes
All good. I think we decided back in 2023 that a test for this particular issue is in scope, and the test is now decoupled as much as possible from specific locale data. Thanks!

2026-09-21 20:07 UTC, merged