proposal-regexp-modifiers: Tests for syntax errors
tc39/test262 pull request #3758
Opened 2022-12-27 00:06 UTC by cjtenny

This covers the syntax error cases from https://github.com/tc39/test262/issues/3756 . Recommend reviewing commit-by-commit, since the third commit is just the result of running the python script to generate the cases. The second commit includes a few non-generated cases written by hand.

2023-01-30 16:22 UTC, gibson042 requested changes
Thanks, this is _excellent_ coverage! A few nits, but I like the overall approach.

2023-02-17 22:07 UTC, cjtenny commented on src/regexp-modifiers/add-remove-multi-duplicate.case
> +m
I think it'd be more clear but duplicate a bit of code - I mostly did it this way to hack being able to reuse cases for arithmetic and non-arithmetic cases. I'll make the change! Or someone else feel free to, see my other note (pending)

2023-02-17 22:07 UTC, cjtenny commented
A belated thanks Richard for the review - I'm unfortunately on medical leave right now so it'll be another month or so before I can return to this. If anybody else wants to take over it in the meantime, feel free, otherwise I'll pick it up as soon as I'm back.

2023-03-31 20:28 UTC, guijemont commented
@gibson042 I've started a new draft PR (https://github.com/tc39/test262/pull/3807) that addresses your comment. Currently a draft PR because the templated test generator does not support the way we format our templates (see https://github.com/tc39/test262/pull/3807#issuecomment-1492571532).

2023-03-31 21:09 UTC, ptomato commented
Closing this in favour of #3807. Thanks, @guijemont!

2023-03-31 21:09 UTC, closed without merging