Add missing iterator-helpers feature flag
tc39/test262 pull request #3855
Opened 2023-06-15 18:14 UTC by syg

2023-06-15 18:15 UTC, syg commented
This is needed because the test was updated on line 29: `assert.sameValue(toString.call(strIter), '[object Iterator]');`

2023-06-15 18:18 UTC, ptomato approved these changes

2023-06-15 18:18 UTC, merged

2026-06-30 01:33 UTC, saifulrizal approved these changes

2026-06-30 01:33 UTC, saifulrizal requested changes
Nice