Add different formatting for test/intl402/DurationFormat/prototype/format/style-digital-en.js
tc39/test262 pull request #3895
Opened 2023-08-12 02:13 UTC by Constellation

ECMA-402 does not require specific CLDR format, and ICU etc. in each platform has some customization for their platform consistency. This PR fixes test/intl402/DurationFormat/prototype/format/style-digital-en.js to adopt different form used in AppleICU.

2023-08-12 02:18 UTC, Constellation commented
@rwaldron @sffc @FrankYFTang

2023-08-14 16:42 UTC, ptomato requested changes
Thanks for the submission. Clearly we need to correct this, as the spec does not mandate a particular locale format, and we should not have a test hardcoded to one engine's output.

However, I'd prefer not to perpetuate the problem by having a test hardcoded to _two_ engines' outputs. See #3786.

You probably know the Intl.DurationFormat spec better than I do here, so what are the essential requirements of formatting `{style: 'digital'}` in English? Could we say that the output must have the number of years, months, weeks, days, hours, minutes, and seconds in order, and that there must be some form of unit (`y.*`, `m.*`, `w.*`, `d.*`) in between the first five quantities, and two colons in between the hours, minutes, and seconds? Maybe there's a regexp that would express that.

(A minor point, if we aren't using `assert.sameValue()` anymore, make sure to include the actual value, and expected value if applicable, in the error message, to help debugging.)

2023-08-14 16:50 UTC, sffc commented
Please also note that the default length for digital units is "short" not "narrow" since https://github.com/tc39/proposal-intl-duration-format/commit/4c24876cb42e2167a65ac4a0c5628cfd40f58cd0

2023-08-14 19:28 UTC, sffc commented
An appropriate test would be one where year/month/day get formatted in default (short) format and then again in digital format, and the results should be the same per the spec.

2023-08-14 20:51 UTC, FrankYFTang commented
How about we change the testing for the duration format to write testing code which use Intl.ListFormat and Intl.NumberFormat to generate expectation and compare with the result produced by the Intl.DurationFormat.

2023-08-14 23:55 UTC, Constellation commented
> An appropriate test would be one where year/month/day get formatted in default (short) format and then again in digital format, and the results should be the same per the spec.

Oops, right. Fixed.

2023-08-14 23:55 UTC, Constellation commented on test/intl402/DurationFormat/prototype/format/style-digital-en.js
> +const expected1 = "1 yr 2 mths 3 wks 3 days 4:05:06";
Changed it to accept comma via RegExp.

2023-08-14 23:57 UTC, Constellation commented
> Thanks for the submission. Clearly we need to correct this, as the spec does not mandate a particular locale format, and we should not have a test hardcoded to one engine's output.
> 
> However, I'd prefer not to perpetuate the problem by having a test hardcoded to _two_ engines' outputs. See #3786.
> 
> You probably know the Intl.DurationFormat spec better than I do here, so what are the essential requirements of formatting `{style: 'digital'}` in English? Could we say that the output must have the number of years, months, weeks, days, hours, minutes, and seconds in order, and that there must be some form of unit (`y.*`, `m.*`, `w.*`, `d.*`) in between the first five quantities, and two colons in between the hours, minutes, and seconds? Maybe there's a regexp that would express that.
> 
> (A minor point, if we aren't using `assert.sameValue()` anymore, make sure to include the actual value, and expected value if applicable, in the error message, to help debugging.)

Changed it to RegExp approach.

2023-08-15 00:05 UTC, ptomato approved these changes
Thanks, works for me, I'll merge it if no-one else suggests any improvements.

2023-08-15 00:51 UTC, sffc approved these changes

2023-08-15 05:50 UTC, anba commented
IMO, applying Frank's suggestion seems the best solution, because it results in the output which is required by the spec:
```js
const parts = [
  new Intl.NumberFormat("en", {style: "unit", unit: "year", unitDisplay: "short"}).format(duration.years),
  new Intl.NumberFormat("en", {style: "unit", unit: "month", unitDisplay: "short"}).format(duration.months),
  new Intl.NumberFormat("en", {style: "unit", unit: "week", unitDisplay: "short"}).format(duration.weeks),
  new Intl.NumberFormat("en", {style: "unit", unit: "day", unitDisplay: "short"}).format(duration.days),
  [
    new Intl.NumberFormat("en", {}).format(duration.hours),
    new Intl.NumberFormat("en", {minimumIntegerDigits: 2}).format(duration.minutes),
    new Intl.NumberFormat("en", {minimumIntegerDigits: 2, minimumFractionDigits: 0, maximumFractionDigits: 9, roundingMode: "trunc"}).format(
      duration.seconds + (duration.milliseconds / 10**3) + (duration.microseconds / 10**6) + (duration.nanoseconds / 10 ** 9)
    ),
  ].join(":")
];
const expected = new Intl.ListFormat("en", {type: "unit", style: "short"}).format(parts);

// And then change the assertion to:
assert.sameValue(df.format(duration), expected, `Assert DurationFormat format output using ${style} style option`);
```

2023-08-15 21:32 UTC, FrankYFTang commented
> > Thanks for the submission. Clearly we need to correct this, as the spec does not mandate a particular locale format, and we should not have a test hardcoded to one engine's output.
> > However, I'd prefer not to perpetuate the problem by having a test hardcoded to _two_ engines' outputs. See #3786.
> > You probably know the Intl.DurationFormat spec better than I do here, so what are the essential requirements of formatting `{style: 'digital'}` in English? Could we say that the output must have the number of years, months, weeks, days, hours, minutes, and seconds in order, and that there must be some form of unit (`y.*`, `m.*`, `w.*`, `d.*`) in between the first five quantities, and two colons in between the hours, minutes, and seconds? Maybe there's a regexp that would express that.
> > (A minor point, if we aren't using `assert.sameValue()` anymore, make sure to include the actual value, and expected value if applicable, in the error message, to help debugging.)
> 
> Changed it to RegExp approach.

Why we need a RegExp to make it ",? " here instead of requiring ", " ? 

In what case the one without "," is the correct expectation?

2023-08-16 04:44 UTC, Constellation commented
@FrankYFTang Currently, just keeping the original expectation since the original test was accepting that.
It seems that this test is added in https://github.com/tc39/test262/commit/4fda9c4c013e5ea4ce723f821a279b037b840c08.
Did you add that based on some ICU configuration?

2023-08-17 06:06 UTC, FrankYFTang commented
> Did you add that based on some ICU configuration?

no, that is based on the spec text prior to the merge of 
https://github.com/tc39/proposal-intl-duration-format/pull/127/files#diff-7d681727fcf47dc0b9a7512a470fb0da63276c625891a5cc232d725bd12912fd

That PR got merged but the test was not updated to sync to that PR. (nor the v8 implementation till https://chromium-review.googlesource.com/c/v8/v8/+/4781659 (which is under review))

2023-08-21 20:14 UTC, Constellation commented
@FrankYFTang OK, I've just changed it to comma split one.
@ptomato Can you merge it?

2023-08-21 21:15 UTC, FrankYFTang approved these changes
LGTM

2023-08-21 22:00 UTC, Constellation commented on test/intl402/DurationFormat/prototype/format/style-digital-en.js
> +const expected2 = "1y, 2mo, 3w, 3d, 4:05:06";
Yes, this is updated in the latest PR.

2023-08-21 22:01 UTC, Constellation commented on test/intl402/DurationFormat/prototype/format/style-digital-en.js
> +const expected = /1 yr,? 2 mths,? 3 wks,? 3 days,? 4:05:06/;
Yes, this is updated in the latest PR :)

2023-08-21 22:36 UTC, ptomato commented
I'd prefer that we implement @anba's suggestion in https://github.com/tc39/test262/pull/3895#issuecomment-1678456244, to avoid hard-coded expectations, but since (1) that's probably not what you signed up for when you opened the PR and (2) it seems like this particular hard-coded output is acceptable to everyone who commented on this thread and does not make the situation worse than it already was, I'll merge it now. See #3786 for follow up.

2023-08-21 22:37 UTC, merged