Add Collator test for ignorePunctuation
tc39/test262 pull request #3913
Opened 2023-09-09 05:21 UTC by FrankYFTang

Test the explicit setting of ignorePunctuation in the option bag reflect to the value in resolvedOptions() under Thai and other locales. (Thai is a special case)

Test the behavior of the compare sync with the value of resolvedOptions().ignorePunctuation

Spec text
https://tc39.es/ecma402/#sec-initializecollator
https://tc39.es/ecma402/#sec-intl.collator.prototype.resolvedoptions
https://tc39.es/ecma402/#sec-collator-comparestrings

2023-09-09 05:22 UTC, FrankYFTang commented
@ben-allen @sffc @anba

2023-09-12 12:50 UTC, Ms2ger requested changes
Thanks. Some comments below

2023-09-12 12:50 UTC, Ms2ger commented on test/intl402/Collator/prototype/compare/ignorePunctuation.js
> +['en','th','ja'].forEach((locale) => {
```suggestion
['en', 'th', 'ja'].forEach((locale) => {
```

2023-09-12 12:50 UTC, Ms2ger commented on test/intl402/Collator/prototype/resolvedOptions/ignorePunctuation-not-default.js
> +['en','th','ja'].forEach((locale) => {
```suggestion
['en', 'th', 'ja'].forEach((locale) => {
```

2023-09-12 12:50 UTC, Ms2ger commented on test/intl402/Collator/prototype/resolvedOptions/ignorePunctuation-not-default.js
> +        .resolvedOptions().ignorePunctuation);
```suggestion
      (new Intl.Collator(locale, {ignorePunctuation}))
          .resolvedOptions().ignorePunctuation,
      ignorePunctuation);
```

2023-09-13 09:29 UTC, Ms2ger approved these changes

2023-09-13 15:48 UTC, merged