Remove locales with explicit u-hc Unicode extension
tc39/test262 pull request #3958
Opened 2023-11-09 12:49 UTC by anba

The tests are passing an explicit `hour12` option, which disables any `hourCycle` option and any `u-hc` Unicode extension. Therefore passing input locales with `u-hc` is invalid.

```js
let locale = "en-u-hc-h24";
let hcDefault = new Intl.DateTimeFormat(locale, { hour: "numeric" }).resolvedOptions().hourCycle;

assert.sameValue(hcDefault, "h24", "hour-cycle through Unicode extension");

let hc24 = new Intl.DateTimeFormat(locale, { hour: "numeric", hour12: false }).resolvedOptions().hourCycle;

// Incorrect assertion, because |hc24| uses |hour12|, which disables any
// hour-cycle option and the hour-cycle is determined from the locale "en".
// That means |hc24| will be "h23".
assert.sameValue(hc24, hcDefault);
```

2024-01-26 12:05 UTC, linusg reviewed
Given:

```
// no locale has "h24" as a default. see https://github.com/tc39/ecma402/pull/758#issue-1622377292
```

This comment / code path no longer seems relevant:

```
// however, "h24" can be set via locale extension.
```

2024-03-01 01:01 UTC, ptomato commented
OK. @ben-allen explained this to me and I think I understand it.

With that understanding (which I may still have gotten wrong), Linus's comment makes sense to me. Maybe the loop body should look something like this?
```js
let hcDefault = new Intl.DateTimeFormat(locale, { hour: "numeric" }).resolvedOptions().hourCycle;
let hcHour12 = new Intl.DateTimeFormat(locale, { hour: "numeric", hour12: true }).resolvedOptions().hourCycle;

assert(hcHour12 === "h11" || hcHour12 === "h12", "Expected hourCycle for hour12: true to be in [\"h11\", \"h12\"]");
if (hcDefault === "h11" || hcDefault === "h12") {
  assert.sameValue(hcHour12, hcDefault);
}

// no locale has "h24" as a default. see https://github.com/tc39/ecma402/pull/758#issue-1622377292
let hcNotHour12 = new Intl.DateTimeFormat(locale, { hour: "numeric", hour12: false }).resolvedOptions().hourCycle;
assert.sameValue(hcNotHour12, "h23", "Expected hourCycle for hour12: false to be \"h23\"");
```

2024-03-01 01:02 UTC, ptomato requested changes
(see previous comment, which I neglected to send as a review comment)

2024-03-09 00:07 UTC, ptomato approved these changes

2024-03-09 00:08 UTC, ptomato commented
OK, fair enough, that seems fine for now.

2024-03-09 00:15 UTC, merged