Array length: add test ensuring RangeError is thrown
tc39/test262 pull request #3974
Opened 2023-12-27 19:00 UTC by ljharb

Turns out v8 fails this test. Discovered by @Jack-Works / @rkirsling in Matrix.

2023-12-27 19:02 UTC, ctcpip requested changes

2023-12-27 19:02 UTC, ctcpip commented on test/built-ins/Array/length/define-own-prop-length-error.js
> +    Object.defineProperty([], 'length', { value: -1, configurable: true });
```suggestion
  Object.defineProperty([], 'length', { value: -1, configurable: true });
```

2023-12-27 19:02 UTC, ctcpip commented on test/built-ins/Array/length/define-own-prop-length-error.js
> +    Object.defineProperty([], 'len' + 'gth', { value: -1, configurable: true });
```suggestion
  // the string is intentionally "computed" here to ensure there are no optimization bugs
  Object.defineProperty([], 'len' + 'gth', { value: -1, configurable: true });
```

2023-12-27 19:25 UTC, rkirsling approved these changes
Thanks!

2023-12-27 19:25 UTC, rkirsling commented on test/built-ins/Array/length/define-own-prop-length-error.js
> +features: []
Evidently this line needs to be dropped.
```suggestion
```

2023-12-27 19:52 UTC, gibson042 approved these changes

2023-12-27 19:54 UTC, ctcpip approved these changes

2023-12-28 03:11 UTC, Jack-Works commented
(actually not by me, @NWYLZW send this in a group)

2024-01-08 14:41 UTC, Ms2ger approved these changes

2024-01-08 14:41 UTC, merged

2024-01-09 02:55 UTC, NWYLZW commented
I submitted an issue in [v8 bugs](https://bugs.chromium.org/p/v8/issues/detail?id=14530).