Fix comment in allow-nlt-before-with.js
tc39/test262 pull request #4001
Opened 2024-02-03 00:08 UTC by lgalfaso

The description of the test states that `WithClause` can be preceded by a line terminator, but the syntax states the opposite.

2024-02-03 04:30 UTC, nicolo-ribaudo requested changes
There is no restriction on line terminators in the proposal spec: https://tc39.es/proposal-import-attributes/#sec-imports. Could you update the syntax comment instead?

2024-02-03 12:35 UTC, lgalfaso commented
Updated the syntax comment.

2024-02-04 00:43 UTC, nicolo-ribaudo approved these changes
Thank you!

2024-02-04 00:45 UTC, nicolo-ribaudo commented
CI failure is unrelated.

2024-02-10 00:35 UTC, ptomato approved these changes
Thanks!

2024-02-10 00:36 UTC, merged