Temporal: Tests for week-numbering algorithm
tc39/test262 pull request #4009
Opened 2024-02-15 17:59 UTC by Aditi-1400

Adds and updates tests for PR: https://github.com/tc39/proposal-temporal/pull/2756

2024-02-19 18:19 UTC, ptomato requested changes
Thanks! All these tests look good, with one comment about needing to move a few of them.

However I think we need to cover a few more things in order to make sure that engines implement every aspect of this normative change:

- In `test/built-ins/`, validation that a custom calendar may return undefined from `yearOfWeek` and `weekOfYear` and that a PlainDate/PlainDateTime/ZonedDateTime with this custom calendar will have the `yearOfWeek`/`weekOfYear` property with the value of undefined
- In `test/intl402/`, a sample case where `iso8601` and `gregory` week numbers disagree according to CLDR

I'm happy to merge this after moving those two tests and add the additional coverage in a follow up, or also happy to re-review this with the additional tests added. Let me know what your preference is.

2024-02-19 18:19 UTC, ptomato commented on test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/non-iso-week-of-year.js
It seems like this one should move to `test/intl402/Temporal/ZonedDateTime/prototype/yearOfWeek/non-iso-week-of-year.js` to match the other similar ones, and also because it will fail if an implementation doesn't include support for non-ISO calendars.

2024-02-19 18:19 UTC, ptomato commented on test/built-ins/Temporal/ZonedDateTime/prototype/weekOfYear/non-iso-week-of-year.js
Same, `test/intl402/Temporal/ZonedDateTime/prototype/weekOfYear/non-iso-week-of-year.js`

2024-02-21 14:04 UTC, Aditi-1400 commented
> Thanks! All these tests look good, with one comment about needing to move a few of them.
> 
> However I think we need to cover a few more things in order to make sure that engines implement every aspect of this normative change:
> 
> * In `test/built-ins/`, validation that a custom calendar may return undefined from `yearOfWeek` and `weekOfYear` and that a PlainDate/PlainDateTime/ZonedDateTime with this custom calendar will have the `yearOfWeek`/`weekOfYear` property with the value of undefined
> * In `test/intl402/`, a sample case where `iso8601` and `gregory` week numbers disagree according to CLDR
> 
> I'm happy to merge this after moving those two tests and add the additional coverage in a follow up, or also happy to re-review this with the additional tests added. Let me know what your preference is.

I've updated the PR to add the tests you requested.

2024-02-21 18:36 UTC, ptomato approved these changes
Thanks for the update, all looks good!

2024-02-21 18:40 UTC, merged