test formatting when microseconds or nanoseconds are the first numeric-styled unit
tc39/test262 pull request #4034
Opened 2024-03-28 16:39 UTC by ben-allen

If `microseconds` are the first `numeric`-styled unit, they should be displayed as a fractional component of milliseconds. Likewise, if `nanoseconds` is the first `numeric`-styled unit, they should be displayed as a fractional component of microseconds.

2024-04-06 01:40 UTC, ptomato reviewed
I didn't get all the way through this one, but I have a couple of questions:
1. If I'm understanding correctly, [GetDurationUnitOptions](https://tc39.es/proposal-intl-duration-format/#sec-getdurationunitoptions) step 4 basically forces `{microseconds: 'numeric'}` and `{nanoseconds: 'numeric'}` to `{microseconds: 'fractional'}` and `{nanoseconds: 'fractional'}` respectively. Do we need test coverage that these things produce the same output?
2. `.format(d.microseconds.toString() + decimalSeparator + d.nanoseconds.toString()))` seems OK for this particular input but it might be better to add `.padStart(3, '0')` to be robust against someone editing the values in `d`.

2024-04-09 20:14 UTC, ptomato requested changes
Finished going through it, and I don't have any additional comments besides what I wrote the other day.

2024-04-11 15:42 UTC, ben-allen commented
Added the padding for the fractional components -- good catch!

With regard to testing for `"fractional"` style: The `"fractional"` style is never directly used by users, who only have `"numeric"` available, and so we don't need to have tests for it. The internal-use-only `"fractional"` style exists for a couple of different reasons:

1. The `"numeric"` style means two dramatically different things, depending on the unit to which it's applied. If the unit is hours, minutes, or seconds, it means something like "format this as on a digital clock", when it's a subsecond unit it means "make this a fractional component of the previously displayed unit". Using the name `"fractional"` simplifies the logic for formatting numeric units, particularly once https://github.com/tc39/proposal-intl-duration-format/pull/188 lands
2. A hypothetical DFv2 could allow users to style durations with fractional components of minutes or hours as well as seconds, milliseconds, and microseconds. In this case making `"fractional"` an actual user-specifiable style rather than just something for internal use would be necessary.

2024-04-11 23:56 UTC, ptomato approved these changes
Okay. `fractional` not being a user-facing option was what I was missing!

2024-04-12 00:02 UTC, merged