`Promise.try`: avoid unneeded syntax
tc39/test262 pull request #4087
Opened 2024-05-17 16:13 UTC by ljharb

Followup to #4086

2024-05-17 17:53 UTC, gibson042 approved these changes
[`throwsAsync`](https://github.com/tc39/test262/blob/57c7d06bf1829f0deec2a2b92b8f5b4a3cdd76f0/harness/asyncHelpers.js#L31) itself is defined as an `async` function, so this is probably moot unless you also update that to be non-async and replace each of its `throw`s to instead return a rejected promise.

2024-05-17 19:03 UTC, ljharb commented
oof, ok fair enough. i'll do that also.

2024-05-17 22:22 UTC, gibson042 requested changes

2024-05-17 22:22 UTC, gibson042 commented on harness/asyncHelpers.js
> +    resolve();
This line will never be reached; it is preceded by `try { return …; } catch (thrown) { …; throw new Test262Error(…); }`. I think you actually want to capture both `resolve` and `reject` in the `new Promise` callback, and replace `return innerThenable.then(…)` with `innerThenable.then(…).then(resolve, reject)`.
```patch
@@ -29,7 +29,7 @@ function asyncTest(testFunc) {
 }
 
 assert.throwsAsync = function (expectedErrorConstructor, func, message) {
-  return new Promise(function (resolve) {
+  return new Promise(function (resolve, reject) {
     var innerThenable;
     if (message === undefined) {
       message = "";
@@ -64,7 +64,7 @@ assert.throwsAsync = function (expectedErrorConstructor, func, message) {
     }
 
     try {
-      return innerThenable.then(
+      innerThenable.then(
         function () {
           message +=
             "Expected a " +
@@ -92,7 +92,7 @@ assert.throwsAsync = function (expectedErrorConstructor, func, message) {
             throw new Test262Error(message);
           }
         }
-      );
+      ).then(resolve, reject);
     } catch (thrown) {
       if (typeof thrown !== "object" || thrown === null) {
         message +=
@@ -109,7 +109,5 @@ assert.throwsAsync = function (expectedErrorConstructor, func, message) {
       }
       throw new Test262Error(message);
     }
-
-    resolve();
   });
 };

```

2024-05-18 15:59 UTC, gibson042 approved these changes

2024-05-18 15:59 UTC, gibson042 commented
LGTM!

2024-05-18 16:30 UTC, merged