chore(ci): Update branch version for ES-META repo
tc39/test262 pull request #4089
Opened 2024-05-18 07:35 UTC by Zaid-maker

Updates the branch version to clone in CI and updates the checkout version to v4

2024-05-20 10:04 UTC, Zaid-maker commented
Anyone review??

2024-05-20 20:04 UTC, jhnaldo commented
@ljharb Yes, I checked that the latest version of ESMeta is compatible with the newest version of Test262. Since the latest version of ESMeta is [v0.4.1](https://github.com/es-meta/esmeta/releases/tag/v0.4.1), I think it is better to update to this version.

I ran all applicable 25,115 Test262 tests and found the following five failed test cases:

1. [`language/expressions/assignment/destructuring/keyed-destructuring-property-reference-target-evaluation-order.js`](https://github.com/tc39/test262/blob/232dfc7b6024490be6bf928f4332fe64b1e24e37/test/language/expressions/assignment/destructuring/keyed-destructuring-property-reference-target-evaluation-order.js)
1. [`language/expressions/assignment/target-super-computed-reference.js`](https://github.com/tc39/test262/blob/232dfc7b6024490be6bf928f4332fe64b1e24e37/test/language/expressions/assignment/target-super-computed-reference.js)
1. [`language/expressions/assignment/destructuring/iterator-destructuring-property-reference-target-evaluation-order.js`](https://github.com/tc39/test262/blob/232dfc7b6024490be6bf928f4332fe64b1e24e37/test/language/expressions/assignment/destructuring/iterator-destructuring-property-reference-target-evaluation-order.js)
1. [`language/expressions/member-expression/computed-reference-null-or-undefined.js`](https://github.com/tc39/test262/blob/232dfc7b6024490be6bf928f4332fe64b1e24e37/test/language/expressions/member-expression/computed-reference-null-or-undefined.js)
1. [`language/expressions/assignment/target-member-computed-reference.js`](https://github.com/tc39/test262/blob/232dfc7b6024490be6bf928f4332fe64b1e24e37/test/language/expressions/assignment/target-member-computed-reference.js)

However, all of them are related to https://github.com/tc39/ecma262/issues/3295 and https://github.com/tc39/ecma262/pull/3307. So, updating the version of ESMeta should be fine.

@Zaid-maker, I'm sorry there has been no update on ESMeta, and thanks for your kind suggestion. From now on, I'll update the version of ESMeta for every release, not only in ecma262 but also in test262.

2024-05-20 20:05 UTC, jhnaldo requested changes
As I explained in the comment, I suggest to update the version of ESMeta to [v0.4.1](https://github.com/es-meta/esmeta/releases/tag/v0.4.1).

2024-05-20 20:05 UTC, jhnaldo commented on .github/workflows/esmeta-test262.yml
> +          git clone --branch v0.4.0 --depth 1 https://github.com/es-meta/esmeta.git "${ESMETA_HOME}"
```suggestion
          git clone --branch v0.4.1 --depth 1 https://github.com/es-meta/esmeta.git "${ESMETA_HOME}"
```

2024-05-21 05:16 UTC, Zaid-maker commented
> As I explained in the comment, I suggest to update the version of ESMeta to [v0.4.1](https://github.com/es-meta/esmeta/releases/tag/v0.4.1).

Ok

2024-05-21 05:24 UTC, jhnaldo approved these changes
LGTM! 👍🏻

2024-05-21 17:21 UTC, ljharb approved these changes

2024-05-21 17:34 UTC, Zaid-maker commented
CI looks happy :)

2024-05-21 17:44 UTC, merged