RAB: Integrate staging tests for the .reduce method
tc39/test262 pull request #4156
Opened 2024-07-16 15:52 UTC by ioannad

of Array.prototype and TypedArray.prototype

This is part of PR #3888 to make reviewing easier. Includes changes to use the helper ./harness/resizableArrayBufferUtils.js

This is the same as .reduceRight in the next PR

2024-07-24 23:29 UTC, ptomato requested changes
Some of the files seem not quite right here.

2024-07-24 23:29 UTC, ptomato commented on test/built-ins/Array/prototype/reduceRight/resizable-buffer-grow-mid-iteration.js
This seems to be an old version of the file that's in #4157.

2024-07-24 23:29 UTC, ptomato commented on test/built-ins/Array/prototype/reduceRight/resizable-buffer.js
Ditto.

2024-07-24 23:29 UTC, ptomato commented on test/built-ins/TypedArray/prototype/reduce/resizable-buffer-grow-mid-iteration.js
This file is testing `map` instead of `reduce`.

2024-07-24 23:29 UTC, ptomato commented on test/built-ins/TypedArray/prototype/reduce/resizable-buffer-shrink-mid-iteration.js
Ditto.

2024-07-24 23:29 UTC, ptomato commented on test/built-ins/TypedArray/prototype/reduceRight/resizable-buffer-grow-mid-iteration.js
Same as above, this looks like an old version of a file in #4157.

2024-07-24 23:29 UTC, ptomato commented on test/built-ins/TypedArray/prototype/reduceRight/resizable-buffer-shrink-mid-iteration.js
Ditto.

2024-07-24 23:29 UTC, ptomato commented on test/built-ins/TypedArray/prototype/reduceRight/resizable-buffer.js
Ditto.

2024-07-25 21:03 UTC, ioannad commented
@ptomato  oh oops! Thank you!

2024-07-29 22:39 UTC, ptomato commented on test/built-ins/TypedArray/prototype/reduce/resizable-buffer-grow-mid-iteration.js
I think you missed a few spots where `map` is still being called.

2024-07-29 23:33 UTC, ioannad commented on test/built-ins/TypedArray/prototype/reduce/resizable-buffer-grow-mid-iteration.js
Thanks!

2024-07-29 23:38 UTC, ioannad commented on test/built-ins/TypedArray/prototype/reduce/resizable-buffer-grow-mid-iteration.js
Done.

2024-07-29 23:39 UTC, ioannad commented on test/built-ins/TypedArray/prototype/reduce/resizable-buffer-shrink-mid-iteration.js
Done.

2024-07-29 23:53 UTC, ptomato approved these changes
Thanks!

2024-07-29 23:54 UTC, ptomato commented
@ioannad Could you rebase this please? I think the removals of the reduceRight files are causing merge conflicts, we want to make sure they stay in-tree when it's merged.

2024-07-30 00:33 UTC, merged