Dont throw when async/generato/asyncGenerator not supported
tc39/test262 pull request #4164
Opened 2024-07-23 16:06 UTC by p-bakker

In order to not fail because harness code fails to load due to using not-supported EcmaScript features while not needed

2024-07-23 22:52 UTC, ptomato requested changes
Thanks for the PR!

I'm less sure about this one, because this harness file is only used in 4 tests which are all guaranteed to fail anyway if async or generators aren't supported. So doesn't really matter if they fail in the harness file.

Or is the problem that you get a SyntaxError instead of a runtime error? (In that case, could we use the `new Function('...')` without swallowing the exception with `catch(e) {}`? I tend not to like unconditionally dropping exceptions...)

2024-07-23 22:52 UTC, ptomato commented on harness/hidden-constructors.js
> +  Object.getPrototypeOf(new Function('async function* () {}')).constructor;
```suggestion
  AsyncGeneratorFunction = Object.getPrototypeOf(new Function('async function* () {}')).constructor;
```

2024-07-23 22:52 UTC, ptomato commented on harness/hidden-constructors.js
> +  Object.getPrototypeOf(new Function('function* () {}')).constructor;
```suggestion
  GeneratorFunction = Object.getPrototypeOf(new Function('function* () {}')).constructor;
```

2024-07-24 00:09 UTC, ljharb approved these changes

2024-07-24 04:14 UTC, p-bakker commented
@ptomato the issue is any error: if for example only one of the three flavors isn't supported, that shouldn't stop/prevent the other two variables from being instantiated.

I don't see how that can be achieved without catching potential exceptions

2024-07-24 16:12 UTC, ptomato commented
Got it, thanks. I understand now.

2024-07-24 16:18 UTC, merged