add tests for "iterator helpers close receiver on argument validation failure"
tc39/test262 pull request #4350
Opened 2024-12-15 05:14 UTC by bakkot

Tests for https://github.com/tc39/ecma262/pull/3467, which has consensus and is just waiting for tests.

No existing tests were invalidated as far as I can tell (presumably because if we'd thought to test this behavior then we'd have updated the proposal instead of needing the PR).

2024-12-15 06:10 UTC, sosukesuzuki commented on test/built-ins/Iterator/prototype/take/argument-validation-failure-closes-underlying.js
> +});
Since the return value of `return` is not an object, wouldn't `TypeError` be thrown before `RangeError` due to step 7 of `IteratorClose`?

2024-12-15 06:14 UTC, sosukesuzuki commented on test/built-ins/Iterator/prototype/take/argument-validation-failure-closes-underlying.js
> +});
Both `Iterator#map` and `Iterator#filter`, etc pass the tests, but they probably do not behave as intended. In all tests, the `return` method of `closable` should return an object, I think.

2024-12-15 06:46 UTC, sosukesuzuki reviewed
Implementing this normative change is likely to cause https://github.com/tc39/test262/blob/main/test/built-ins/Iterator/prototype/reduce/non-callable-reducer.js to start failing, because the underlying iterator will already be closed during the second call to `reduce`.

2025-01-08 23:23 UTC, bakkot commented
Thanks for the review @sosukesuzuki, addressed comments.

2025-01-12 05:12 UTC, sosukesuzuki approved these changes

2025-01-31 01:04 UTC, ptomato requested changes
Thanks. Two comments, but they apply to multiple files.

2025-02-03 20:28 UTC, bakkot commented on test/built-ins/Iterator/prototype/drop/argument-validation-failure-closes-underlying.js
> +  __proto__: Iterator.prototype,
The syntax form is not optional, it's only the getter/setter on Object.prototype.

2025-02-03 20:39 UTC, ptomato commented on test/built-ins/Iterator/prototype/drop/argument-validation-failure-closes-underlying.js
> +  __proto__: Iterator.prototype,
Makes sense, thanks. Disregard this then.

2025-02-03 20:42 UTC, bakkot commented on test/built-ins/Iterator/prototype/drop/argument-validation-failure-closes-underlying.js
> +});
Done.

2025-02-03 20:43 UTC, ptomato approved these changes
Thanks!

2025-02-04 19:32 UTC, merged